FROM nginx:latest

LABEL maintainer="natandias1"

USER root

RUN apt-get update && apt-get install \
    git -y

WORKDIR /usr/share/nginx/html

RUN rm -rf /usr/share/nginx/html/*

RUN git clone https://github.com/natan-dias/webserver-example-src.git .

USER nginx

EXPOSE 80 443
