FROM nginx:latest
USER root
RUN apt-get update && apt-get install \
    git -y
WORKDIR /usr/share/nginx/html
RUN rm -rf /usr/share/nginx/html/*
RUN git clone https://github.com/natan-dias/webserver-example-src.git .
EXPOSE 80 443

