apiVersion: v1
kind: Secret
metadata:
  name: secret-nginx.local
  namespace: nginx
  labels:
    app.kubernetes.io/instance: argo-spark
type: kubernetes.io/tls
data:
  tls.crt: fake-certificates/domain.crt
  tls.key: fake-certificates/domain.key