version: "3.3"
services:
  spark-main:
    image: natandias1/spark-base:1.0.8
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-main
      - SPARK_WORKLOAD=master
  spark-node-a:
    image: natandias1/spark-base:1.0.8
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-main
    environment:
      - SPARK_MASTER=spark://spark-main:7077
      - SPARK_NODE_CORES=1
      - SPARK_NODE_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-node-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  #demo-database:
  #  image: postgres:11.7-alpine
  #  ports: 
  #    - "5432:5432"
  #  environment: 
  #    - POSTGRES_PASSWORD=casa1234
