apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-edit-binding
subjects:
- kind: ServiceAccount
  name: spark
  namespace: spark
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io