kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-kind-cluster
networking:
  podSubnet: 10.0.0.0/16
  serviceSubnet: 10.10.0.0/16
  ipFamily: ipv4
  apiServerAddress: 127.0.0.1

# Releases https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
nodes:
- role: control-plane
  image: kindest/node:v1.33.1@sha256:8d866994839cd096b3590681c55a6fa4a071fdaf33be7b9660e5697d2ed13002
  labels:
    ingress-ready: true
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

- role: worker
  image: kindest/node:v1.33.1@sha256:8d866994839cd096b3590681c55a6fa4a071fdaf33be7b9660e5697d2ed13002
  labels:
    group: dev
  extraMounts:
  - hostPath: /Users/natandias/workspace/kind
    containerPath: /data
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP