---
apiVersion: v1
kind: Service
metadata:
  name: spark-main
  namespace: spark
spec:
  type: ClusterIP
  selector:
    service: spark
  ports:
    - name: main-port
      port: 7077
      targetPort: 7077
    - name: spark-main-web-port
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-node
  namespace: spark
spec:
  type: ClusterIP
  selector:
    service: spark-node
  ports:
    - name: node-port
      port: 8080
      targetPort: 8080
    - name: node-port-2
      port: 7000
      targetPort: 7000