namespace: spark
resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - spark.yaml
  - spark-worker.yaml
  - storage.yaml

secretGenerator:
  - name: secret-spark.local
    files:
      - tls.key=fake-certificates/domain.key
      - tls.crt=fake-certificates/domain.crt
    type: "kubernetes.io/tls"
