namespace: spark
resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - spark.yaml
  - spark-worker.yaml
  - storage.yaml

secretGenerator:
  - name: secret-spark.local
    files:
      - tls.key=<path:cubbyhole/spark-base#spark-local.key>
      - tls.crt=<path:cubbyhole/spark-base#spark-local.crt>
    type: "kubernetes.io/tls"
