apiVersion: v1
kind: Secret
metadata:
  name: secret-spark.local
  namespace: spark
  annotations:
    avp.kubernetes.io/path: "vault/data/spark-base"
  labels:
    app.kubernetes.io/instance: argo-spark
type: kubernetes.io/tls
data:
  tls.crt: <spark.local.crt>
  tls.key: <spark.local.key>