apiVersion: v1
kind: Secret
metadata:
  name: secret-spark.local
  namespace: spark
type: Opaque
data:
  tls.crt: <path:vault/data/spark-base#spark-local.crt>
  tls.key: <path:vault/data/spark-base#spark-local.key>