---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-apps
  namespace: spark
spec:
  storageClassName: data
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/spark-apps
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data
  namespace: spark
spec:
  storageClassName: data
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/spark-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-apps
  namespace: spark
  finalizers: null # Only on lab environment
spec:
  storageClassName: "data"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500m
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data
  namespace: spark
  finalizers: null # Only on lab environment
spec:
  storageClassName: "data"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500m