apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:natan-dias/my-devops-repo.git
    targetRevision: main
    path: infra/redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    automated:
      selfHeal: true
      prune: true