FROM mysql:9.3.0

# Change Database user and database name by some parameters
ENV MYSQL_ROOT_PASSWORD=$dbrootpassword \
    MYSQL_DATABASE=$dbname \ 
    MYSQL_USER=$dbuser \
    MYSQL_PASSWORD=$dbpassword

EXPOSE 3306
