apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgresql
  storageClassName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: knowledge-base-app
spec:
  storageClassName: "data"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi