apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
- ingress.yaml

secretGenerator:
  - name: secret-argocd.local
    files:
      - tls.key=certs/domain.key
      - tls.crt=certs/domain.crt
    type: "kubernetes.io/tls"
