apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
data:
  VAULT_ADDR: aHR0cDovL3ZhdWx0LmxvY2Fs
  VAULT_TOKEN: YOUR_VAULT_TOKEN
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: dG9rZW4=
type: Opaque
