name: CI Build and Push on MERGE

on:

  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
    push-on-merge:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
        - name: Checkout repo
          uses: actions/checkout@v3.5.2

        - name: Download image name artifact
          uses: actions/download-artifact@v3
          with:
            name: image_name

        - name: Read image name from artifact
          id: image-name
          run: |
            IMAGE_NAME=$(cat image_name.txt)
            echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

        - name: Log in to Docker Hub
          uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Set Repo Name
          id: repo-name
          run: |
            echo "REPO=natandias1" >> $GITHUB_ENV
        
        - name: Docker Metadata action
          id: meta
          uses: docker/metadata-action@v4.4.0
          with:
            images: ${{ env.REPO }}/${{ steps.image-name.outputs.IMAGE_NAME }}
            tags: latest
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v5.3.0
          with:
            file: ${{ steps.image-name.outputs.IMAGE_NAME }}/Dockerfile
            context: .
            tags: latest
        
        - name: Check status
          run: | 
            echo "Dockerfile check complete"
            echo "Docker image name: ${{ env.REPO }}/${{ steps.image-name.outputs.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}"
