name: CI to Docker Hub

on:
  workflow_dispatch:
    branches:
      - main
    tags: [ 'v*' ]
    inputs:
      folder: 
        description: 'Dockerfile folder location'
        required: true
        type: string
        default: './images/'
      release_tag:
        description: 'Release tag'
        required: true
        type: string
        default: 'latest'

jobs:
  build-docker-image-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set Repo Name
      run: |
        echo "REPO=natandias1" >> $GITHUB_ENV
        echo "Repo name: ${{ env.REPO }}"
    
    - name: "Set envs"
      id: set-envs
      run: | 
        IMAGE_NAME_FOLDER=$(awk -F "/" '{print $NF}' <<< ${{ github.event.inputs.folder }})
        echo "IMAGE_NAME_FOLDER=$IMAGE_NAME_FOLDER" >> $GITHUB_ENV
        echo "Image name folder: $IMAGE_NAME_FOLDER"

    - name: Build and Push Docker Image
      id: build-and-push
      run: |
        docker build -t ${{ env.REPO }}/${{ env.IMAGE_NAME_FOLDER }}:${{ github.event.inputs.release_tag }} -f ${{ github.event.inputs.folder }}/Dockerfile .
        docker push ${{ env.REPO }}/${{ env.IMAGE_NAME_FOLDER }}:${{ github.event.inputs.release_tag }}
    
    #- name: Docker Metadata action
    #  id: meta
    #  uses: docker/metadata-action@v4.4.0
    #  with:
    #    images: ${{ env.REPO }}/${{ env.IMAGE_NAME_FOLDER }}
    #    tags: |
    #      type=ref,event=branch
    #      type=ref,event=tag
    #      type=semver,pattern={{major}}.{{minor}}.{{patch}}
    #  
    #- name: Build and push Docker images
    #  uses: docker/build-push-action@v4.0.0
    #  with:
    #    file: ${{ github.event.inputs.folder }}/Dockerfile
    #    context: .
    #    tags: ${{ steps.meta.outputs.tags }}
    #    push: ${{ github.event_name != 'pull_request' }}
