name: Manual CI to Docker Hub

on:
  workflow_dispatch:
    branches:
      - main
    tags: [ 'v*' ]
    inputs:
      folder: 
        description: 'Dockerfile folder location'
        required: true
        type: string
        default: './images/'
      release_tag:
        description: 'Release tag'
        required: true
        type: string
        default: 'latest'

jobs:
  set-envs:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      lastReleaseTag: ${{ steps.get_last_release_tag.outputs.lastReleaseTag }}
      IMAGE_NAME_FOLDER: ${{ steps.set-image-name.outputs.IMAGE_NAME_FOLDER }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
    
    - name: "Set image name folder"
      id: set-image-name
      run: | 
        IMAGE_NAME_FOLDER=$(awk -F "/" '{print $NF}' <<< ${{ github.event.inputs.folder }})
        echo "IMAGE_NAME_FOLDER=$IMAGE_NAME_FOLDER" >> $GITHUB_OUTPUT
        echo "Image name folder: $IMAGE_NAME_FOLDER"
    
    - name: Get Last release tag
      uses: actions/github-script@v3
      id: get_last_release_tag
      with:
        script: |
          const { data: releases } = await github.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });

          const lastReleaseTag = releases[0].tag_name;
          core.setOutput('lastReleaseTag', lastReleaseTag);

          console.log(`Last release tag: ${lastReleaseTag}`);

  build-docker-image-and-push:
    name: Build and Push Docker Image
    needs: set-envs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Repo Name
      id: repo-name
      run: |
        echo "REPO=natandias1" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      id: build-and-push
      run: |
        docker build -t ${{ env.REPO }}/${{ needs.set-envs.outputs.IMAGE_NAME_FOLDER }}:${{ needs.set-envs.outputs.lastReleaseTag }} -f ${{ github.event.inputs.folder }}/Dockerfile .
        docker push ${{ env.REPO }}/${{ needs.set-envs.outputs.IMAGE_NAME_FOLDER }}:${{ needs.set-envs.outputs.lastReleaseTag }}
