name: Codecov Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Test python scripts
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync --extra dev
      working-directory: scripts
    - name: Run tests and collect coverage
      run: uv run python -m pytest --cov . tests/
      working-directory: scripts
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}