name: Dockerfile Check CI

on:
  pull_request:
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AFFECTED_FOLDER:

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install docker

    - name: Determine affected folder
      run: |
        PR_BRANCH=$(echo $GITHUB_REF | cut -d"/" -f3)
        AFFECTED_FOLDER=$(git diff --name-only HEAD -- $PR_BRANCH | grep 'Dockerfile' | xargs -I {} dirname {} | sort -u)
        echo "AFFECTED_FOLDER=$AFFECTED_FOLDER" >> $GITHUB_ENV

    - name: Run script to check Dockerfile changes and build Docker image
      run: python scripts/build_and_push.py $AFFECTED_FOLDER

    - name: Check status
      run: echo "Dockerfile check complete"