name: Dockerfile Check CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Set up Python
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: '3.x'

    #- name: Install dependencies
    #  run: pip install docker

    - name: Determine affected folder
      run: |
        git remote update
        git fetch
        AFFECTED_FOLDER=$(git diff --name-only origin/main..origin/${{ github.head_ref }} | grep 'Dockerfile' | xargs -I {} dirname {} | sort -u)
        echo "AFFECTED_FOLDER=$AFFECTED_FOLDER" >> $GITHUB_ENV
        echo "Affected folders: $AFFECTED_FOLDER"

    #- name: Run script to check Dockerfile changes and build Docker image
    #  run: python scripts/build_and_push.py $AFFECTED_FOLDER

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: |
          natandias1/${{ env.AFFECTED_FOLDER}}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        file: ${{ env.AFFECTED_FOLDER }}/Dockerfile
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name == 'pull_request' }}
    
    - name: Check status
      run: echo "Dockerfile check complete"