name: CI Build and Push

on:
  pull_request:
    branches: [ "main" ]

  push:
    branches: [ "main" ]

jobs:
  check-dockerfile-changes:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      affected_folder: ${{ steps.affected-folder.outputs.AFFECTED_FOLDER }}
      image_name_folder: ${{ steps.affected-folder.outputs.IMAGE_NAME_FOLDER }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine affected folder
      id: affected-folder
      run: |
        git remote update
        git fetch
        AFFECTED_FOLDER=$(git diff --name-only origin/main..origin/${{ github.head_ref }} | grep -i 'Dockerfile' | xargs -I {} dirname {} | sort -u)
        IMAGE_NAME_FOLDER=$(git diff --name-only origin/main..origin/${{ github.head_ref }} | grep -i 'Dockerfile' | xargs -I {} dirname {} | sort -u | awk -F/ '{print $(NF-0)}')
        echo "AFFECTED_FOLDER=$AFFECTED_FOLDER" >> $GITHUB_OUTPUT
        echo "IMAGE_NAME_FOLDER=$IMAGE_NAME_FOLDER" >> $GITHUB_OUTPUT
        echo "Affected folders: $AFFECTED_FOLDER"
        echo "Image name folder: $IMAGE_NAME_FOLDER"

        if [[ $AFFECTED_FOLDER == '' ]]; then
          echo "========= No Dockerfile affected on this PR ========="
          exit 0
        fi
    
    - name: Set Repo Name
      id: repo-name
      run: |
        echo "REPO=natandias1" >> $GITHUB_OUTPUT
  
  build-and-push:
    needs: check-dockerfile-changes
    if: ${{ github.event_name == 'pull_request' && needs.check-dockerfile-changes.outputs.AFFECTED_FOLDER != '' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Repo Name
      id: repo-name
      run: |
        echo "REPO=natandias1" >> $GITHUB_ENV

    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ${{ env.REPO }}/${{ needs.check-dockerfile-changes.outputs.IMAGE_NAME_FOLDER }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
        flavor: |
          latest=false
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        file: ${{ needs.check-dockerfile-changes.outputs.AFFECTED_FOLDER }}/Dockerfile
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name == 'pull_request' }}
    
    - name: Check status
      run: | 
        echo "Dockerfile check complete"
        echo "Docker image name: ${{ needs.check-dockerfile-changes.outputs.IMAGE_NAME_FOLDER }}"
        echo "Affected folders: ${{ needs.check-dockerfile-changes.outputs.AFFECTED_FOLDER }}"
        echo "Docker image tags: ${{ steps.meta.outputs.tags }}"
    
  build-and-push-latest-on-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.action == 'push' && needs.check-dockerfile-changes.outputs.AFFECTED_FOLDER != '' }}
    needs: check-dockerfile-changes
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.5.2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ${{ env.REPO }}/${{ needs.check-dockerfile-changes.outputs.IMAGE_NAME_FOLDER }}
        tags: latest
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        file: ${{ needs.check-dockerfile-changes.outputs.AFFECTED_FOLDER }}/Dockerfile
        context: .
        tags: latest
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name == 'push' }}

